#!/usr/bin/env python3
"""
Example script to inspect the unlabelled, messy IoT data generated by the pipeline.
Shows sample records, missing values, anomalies, and data quality issues.
"""

import pandas as pd
import numpy as np
from src.data_preprocessing import create_real_unlabelled_messy_iot_data

# Generate sample data
print("Generating sample unlabelled, messy IoT network data...")
df = create_real_unlabelled_messy_iot_data(n_samples=1000, n_devices=20, seed=42)

print("\n" + "="*80)
print("SAMPLE RECORDS (first 10)")
print("="*80)
print(df.head(10).to_string())

print("\n" + "="*80)
print("DATA QUALITY ISSUES ANALYSIS")
print("="*80)

# Missing values
missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
print("\nMISSING VALUES:")
for col in missing[missing > 0].index:
    print(f"  {col:<20}: {missing[col]:>4} ({missing_pct[col]:>5.1f}%)")

# Data type issues
print("\nDATA TYPE DISTRIBUTION:")
for col in df.columns:
    try:
        numeric = pd.to_numeric(df[col], errors='coerce').notna().sum()
        strings = (~pd.to_numeric(df[col], errors='coerce').notna()).sum()
        if strings > 0:
            print(f"  {col:<20}: Numbers={numeric:>5}  |  Strings/Invalid={strings:>4}")
    except:
        pass

# Duplicates
dup_count = df.duplicated().sum()
print(f"\nDUPLICATE RECORDS: {dup_count} (~{100*dup_count/len(df):.1f}%)")

# Anomalous values
print("\nANOMALOUS NUMERIC VALUES:")
numeric_cols = df.select_dtypes(include=[np.number]).columns
for col in numeric_cols:
    if col in df.columns:
        negative = (df[col] < 0).sum()
        if negative > 0:
            print(f"  {col:<20}: {negative:>3} negative values")

# Example "messy" records
print("\n" + "="*80)
print("EXAMPLES OF MESSINESS")
print("="*80)

# Find records with NaN
nan_examples = df[df.isnull().any(axis=1)].head(3)
print("\nRecords with Missing Values:")
for idx, row in nan_examples.iterrows():
    print(f"\n  Record {idx}:")
    for col, val in row.items():
        if pd.isna(val):
            print(f"    {col}: [MISSING]")
        else:
            print(f"    {col}: {val}")

# Find records with string errors
print("\n\nRecords with Invalid Values:")
for idx, row in df[df['src_ip'] == '999.999.999.999'].head(2).iterrows():
    print(f"\n  Record {idx} - Invalid IP:")
    print(f"    src_ip: {row['src_ip']} ⚠️ INVALID")
    print(f"    dst_ip: {row['dst_ip']}")

# Statistical summary of "normal" looking numerical data
print("\n" + "="*80)
print("STATISTICAL SUMMARY (Numeric Columns)")
print("="*80)
print(df[['packet_count', 'byte_count', 'duration']].describe())

print("\n" + "="*80)
print("KEY INSIGHT")
print("="*80)
print("""
This dataset simulates real-world IoT network traffic with ZERO labels.

Real-World Characteristics:
  • Missing sensor data (network timeouts, dropped packets)
  • Corrupted log entries from faulty devices
  • Inconsistent protocol implementations across vendors
  • Invalid entries from misconfigured equipment
  • Duplicate transmissions due to network retries
  • Anomalous patterns mixed with normal traffic (UNLABELED)

The pipeline handles this by:
  1. Imputing missing values with statistical methods
  2. Converting mismatched data types
  3. Normalizing features for graph construction
  4. Using K-means to discover natural clusters (pseudo-labels)
  5. Training GNNs on the pseudo-labeled data

Result: Models learn to separate data clusters WITHOUT ground truth!
""")
